### ISSUE TITLE
Support Angular 13.1.0

### ISSUE THREAD

**Issue by ttimot24** [pjlamb12/angular-svg-icon-preloader#11]
## I'm submitting a bug/feature request

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
```
npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: angular-cfo@0.0.0
npm ERR! Found: @angular/common@13.1.0
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~13.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^12.0.0" from angular-svg-icon-preloader@2.0.1
npm ERR! node_modules/angular-svg-icon-preloader
npm ERR!   angular-svg-icon-preloader@"^2.0.1" from the root project
```

## Expected behavior

The library does not have dependency issue with Angular 13

## Minimal reproduction of the problem with instructions

Update angular/core at least v13

## Environment

<pre><code>
Angular version: 13.1.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  v15.12.0
- Platform:  Linux

Others:

</code></pre>

**Comment by Qumatah** [comment]
Hi, I'm also trying version 3.0.0 since we are migrating to angular 13 (using version 13.3.11 atm). Could you add support for this by upping the npm dependencies? Something like `^13.0.0` would be ideal for all Angular 13 users.

**Comment by Qumatah** [comment]
To clarify, the issue is with the following peerDependency: `"@angular/platform-browser-dynamic": "13.2.0"` I would like to see `"@angular/platform-browser-dynamic": "^13.2.0"` there
