### ISSUE TITLE
Support default icon 

### ISSUE THREAD

**Issue by ttimot24** [pjlamb12/angular-svg-icon-preloader#14]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently many 404 exceptions are thrown is an icon not found. This can be a problem when icon name generated dynamically based on data.

## Expected behavior

Please support a default icon mode

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by pjlamb12** [comment]
I'm not sure what you mean on this; can you explain it a little more? As long as you load an icon with a given name, it'll work and use that icon.

**Comment by pjlamb12** [comment]
Yeah, I think that request belongs on the actual SVG icon package. All this library does is load the icons you want to use up front instead of having to do it in each component.
