### ISSUE TITLE
Provider question

### ISSUE THREAD

**Issue by ross1296** [pjlamb12/angular-svg-icon-preloader#21]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Is this the correct approach to using angular-svg-icon-preloader if using `provideAngularSvgIcon()`? This is an Angular 18.2.2 application using `bootstrapApplication()`
```typescript
provideAngularSvgIcon(),
importProvidersFrom(
  AngularSvgIconPreloaderModule.forRoot({
    configUrl: 'assets/svg-icons.json',
  })
),
```

**Comment by pjlamb12** [comment]
Yes, this should be correct and it should work that way.
